# Generated by Django 5.2.4 on 2025-07-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='schema_markup',
            field=models.TextField(blank=True, help_text='Paste JSON-LD schema markup here', null=True),
        ),
    ]
