# Generated by Django 5.2.4 on 2025-07-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='schema_markup',
            field=models.TextField(blank=True, help_text='Add custom JSON-LD schema here', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='schema_markup',
            field=models.TextField(blank=True, help_text='Add custom JSON-LD schema here', null=True),
        ),
    ]
