# Generated by Django 5.2.4 on 2025-07-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/meta_images/'),
        ),
    ]
