# Generated by Django 4.1.7 on 2025-07-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='mission_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='mission_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='philosophy_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='philosophy_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='values_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='values_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='vision_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='vision_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
