# Generated by Django 4.1.7 on 2025-07-14 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_staticpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaticPage',
            new_name='LegalstaticPage',
        ),
    ]
