# Generated by Django 4.1.7 on 2025-07-14 06:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_staticpage_legalstaticpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalstaticpage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
