# Generated by Django 4.1.7 on 2025-07-14 09:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_legalstaticpage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
