# Generated by Django 4.1.7 on 2025-07-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_checkblog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='checkBlog',
        ),
    ]
