# Generated by Django 4.1.7 on 2025-07-15 04:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_checkblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='homepage/meta_images/')),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('twitter_title', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('robots_tag', models.CharField(default='INDEX, FOLLOW, MAX-IMAGE-PREVIEW:LARGE, MAX-SNIPPET:-1, MAX-VIDEO-PREVIEW:-1', max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('schema_markup', models.TextField(blank=True, help_text='Add custom JSON-LD schema here', null=True)),
                ('main_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('description_paragraph', models.TextField(blank=True, null=True)),
                ('icon1_image', models.ImageField(blank=True, null=True, upload_to='homepage/icons/')),
                ('icon1_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('icon1_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('icon1_subtext', models.CharField(blank=True, max_length=255, null=True)),
                ('icon2_image', models.ImageField(blank=True, null=True, upload_to='homepage/icons/')),
                ('icon2_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('icon2_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('icon2_subtext', models.CharField(blank=True, max_length=255, null=True)),
                ('icon3_image', models.ImageField(blank=True, null=True, upload_to='homepage/icons/')),
                ('icon3_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('icon3_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('icon3_subtext', models.CharField(blank=True, max_length=255, null=True)),
                ('icon4_image', models.ImageField(blank=True, null=True, upload_to='homepage/icons/')),
                ('icon4_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('icon4_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('icon4_subtext', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('about_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about_section/images/')),
                ('about_image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('video_url', models.URLField(blank=True, help_text='Paste a YouTube or .mp4 URL', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
